baseURL = 'https://enexam.github.io/maxence_blog/'
languageCode = 'en-us'
title = 'Maxence Beuselinck'
theme = 'rusty-typewriter'

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[rusty_typewriter]
 [params.rtwt]
  sidePane = true
  countPageItems = 7 

 [params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

 [params.rtwt.side.home]
  sidePaneSticky = false 
  taxonomies = ['tags', 'categories']
  countTaxonomy = 5

 [params.rtwt.side.list]
  sidePaneSticky = false

 [params.rtwt.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

 [taxonomies]
  tag = 'tags'
  category = 'categories'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'GNU Radio modules'
    pageRef = '/gnuradio_modules/'
    weight = 2
  [[menus.main]]
    name = 'Ground station'
    pageRef = '/ground_station/'
    weight = 3
  [[menus.main]]
    name = 'About me'
    pageRef = '/about_me'
    weight = 4
